apiVersion: v1
kind: Secret
metadata:
  name: manafood-secrets
type: Opaque
data:
  ConnectionStrings__MySql: c2VydmVyPWRiLW1hbmEtZm9vZDtwb3J0PTMzMDY7ZGF0YWJhc2U9ZGJfbWFuYWZvb2Q7dXNlcj1yb290O3Bhc3N3b3JkPXNlbmhhMTIz
