# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "[2 - Action Full CD]" # CI/CD Pipeline - C# (.NET) 

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write   

jobs:
  # 1. Build e Testes
  build-and-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restaurar dependências
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Rodar Testes
      run: dotnet test --configuration Release --no-build --verbosity normal
